// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using couvre_plancher.Data;

#nullable disable

namespace couvre_plancher.Migrations
{
    [DbContext(typeof(AplicationDbContext))]
    [Migration("20230324135024_all_models")]
    partial class all_models
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("couvre_plancher.Models.ClientModel", b =>
                {
                    b.Property<int>("Cin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Cin"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("adresse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("num")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Cin");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("couvre_plancher.Models.CommandeModel", b =>
                {
                    b.Property<int>("Id_cmd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_cmd"));

                    b.Property<int?>("Cin")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Id_couvre")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("date_cmd")
                        .HasColumnType("datetime2");

                    b.HasKey("Id_cmd");

                    b.HasIndex("Cin");

                    b.HasIndex("Id_couvre");

                    b.ToTable("Commande");
                });

            modelBuilder.Entity("couvre_plancher.Models.CouvreplancherModel", b =>
                {
                    b.Property<int>("Id_couvre")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_couvre"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("image_couvre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("main_oeuvre")
                        .HasColumnType("float");

                    b.Property<double>("materieaux")
                        .HasColumnType("float");

                    b.HasKey("Id_couvre");

                    b.ToTable("Couvreplancher");
                });

            modelBuilder.Entity("couvre_plancher.Models.PackModel", b =>
                {
                    b.Property<int>("Id_pack")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_pack"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Id_couvre")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("reduction")
                        .HasColumnType("int");

                    b.Property<float>("superficie")
                        .HasColumnType("real");

                    b.HasKey("Id_pack");

                    b.HasIndex("Id_couvre");

                    b.ToTable("Pack");
                });

            modelBuilder.Entity("couvre_plancher.Models.PromotionModel", b =>
                {
                    b.Property<int>("Id_pro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_pro"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Id_couvre")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("evenement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("reduction")
                        .HasColumnType("int");

                    b.HasKey("Id_pro");

                    b.HasIndex("Id_couvre");

                    b.ToTable("Promotion");
                });

            modelBuilder.Entity("couvre_plancher.Models.SuperviseurModel", b =>
                {
                    b.Property<int>("Id_sup")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_sup"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_sup");

                    b.ToTable("Superviseur");
                });

            modelBuilder.Entity("couvre_plancher.Models.CommandeModel", b =>
                {
                    b.HasOne("couvre_plancher.Models.ClientModel", "id_client")
                        .WithMany()
                        .HasForeignKey("Cin");

                    b.HasOne("couvre_plancher.Models.CouvreplancherModel", "id_couvre")
                        .WithMany()
                        .HasForeignKey("Id_couvre");

                    b.Navigation("id_client");

                    b.Navigation("id_couvre");
                });

            modelBuilder.Entity("couvre_plancher.Models.PackModel", b =>
                {
                    b.HasOne("couvre_plancher.Models.CouvreplancherModel", "id_couvre")
                        .WithMany()
                        .HasForeignKey("Id_couvre");

                    b.Navigation("id_couvre");
                });

            modelBuilder.Entity("couvre_plancher.Models.PromotionModel", b =>
                {
                    b.HasOne("couvre_plancher.Models.CouvreplancherModel", "id_couvre")
                        .WithMany()
                        .HasForeignKey("Id_couvre");

                    b.Navigation("id_couvre");
                });
#pragma warning restore 612, 618
        }
    }
}
